# Project: Assign2
# Makefile created by Dev-C++ 4.9.9.2

CPP  = g++.exe
CC   = gcc.exe
WINDRES = windres.exe
RES  = 
OBJ  = ../main.o ../menu.o ../queue.o ../stack.o $(RES)
LINKOBJ  = ../main.o ../menu.o ../queue.o ../stack.o $(RES)
LIBS =  -L"C:/Dev-Cpp/lib"  
INCS =  -I"C:/Dev-Cpp/include" 
CXXINCS =  -I"C:/Dev-Cpp/lib/gcc/mingw32/3.4.2/include"  -I"C:/Dev-Cpp/include/c++/3.4.2/backward"  -I"C:/Dev-Cpp/include/c++/3.4.2/mingw32"  -I"C:/Dev-Cpp/include/c++/3.4.2"  -I"C:/Dev-Cpp/include" 
BIN  = Assign2.exe
CXXFLAGS = $(CXXINCS)  
CFLAGS = $(INCS)  
RM = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before Assign2.exe all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o "Assign2.exe" $(LIBS)

../main.o: ../main.cpp
	$(CPP) -c ../main.cpp -o ../main.o $(CXXFLAGS)

../menu.o: ../menu.cpp
	$(CPP) -c ../menu.cpp -o ../menu.o $(CXXFLAGS)

../queue.o: ../queue.cpp
	$(CPP) -c ../queue.cpp -o ../queue.o $(CXXFLAGS)

../stack.o: ../stack.cpp
	$(CPP) -c ../stack.cpp -o ../stack.o $(CXXFLAGS)
